/**
 * Offline locale bundles — one JSON file per supported language.
 * Generated by: node scripts/generate-all-locales.js
 * English source of truth: scripts/en-flat.json → locales/en.json
 */
import en from '../locales/en.json';
import es from '../locales/es.json';
import fr from '../locales/fr.json';
import de from '../locales/de.json';
import it from '../locales/it.json';
import pt from '../locales/pt.json';
import nl from '../locales/nl.json';
import pl from '../locales/pl.json';
import ru from '../locales/ru.json';
import zh from '../locales/zh.json';
import ja from '../locales/ja.json';
import ko from '../locales/ko.json';
import ar from '../locales/ar.json';
import hi from '../locales/hi.json';
import tr from '../locales/tr.json';
import sv from '../locales/sv.json';
import da from '../locales/da.json';
import no from '../locales/no.json';
import fi from '../locales/fi.json';

export const LOCAL_TRANSLATION_BUNDLES: Record<string, Record<string, string>> = {
  en,
  es,
  fr,
  de,
  it,
  pt,
  nl,
  pl,
  ru,
  zh,
  ja,
  ko,
  ar,
  hi,
  tr,
  sv,
  da,
  no,
  fi,
};

/** All supported UI languages with full offline translation coverage */
export const UI_FULL_COVERAGE_LANGUAGES = [
  'en',
  'es',
  'fr',
  'de',
  'it',
  'pt',
  'nl',
  'pl',
  'ru',
  'zh',
  'ja',
  'ko',
  'ar',
  'hi',
  'tr',
  'sv',
  'da',
  'no',
  'fi',
] as const;

export type FullCoverageLanguage = (typeof UI_FULL_COVERAGE_LANGUAGES)[number];

/** Display metadata for the 19 offline UI languages (picker + localeInfo) */
export const LOCAL_LANGUAGE_META: Array<{
  code: FullCoverageLanguage;
  name: string;
  nativeName: string;
  direction: 'ltr' | 'rtl';
}> = [
  { code: 'en', name: 'English', nativeName: 'English', direction: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', direction: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', direction: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', direction: 'ltr' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', direction: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', direction: 'ltr' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', direction: 'ltr' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', direction: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', direction: 'ltr' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', direction: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', direction: 'ltr' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', direction: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', direction: 'rtl' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', direction: 'ltr' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', direction: 'ltr' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', direction: 'ltr' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', direction: 'ltr' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', direction: 'ltr' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', direction: 'ltr' },
];

const RTL_LANGUAGES = new Set(['ar']);

export function resolveLocaleDirection(langCode: string): 'ltr' | 'rtl' {
  return RTL_LANGUAGES.has(langCode) ? 'rtl' : 'ltr';
}

export function resolveLocaleNativeName(langCode: string): string {
  return LOCAL_LANGUAGE_META.find((l) => l.code === langCode)?.nativeName || langCode;
}

export function hasLocalTranslationBundle(langCode: string): boolean {
  const bundle = LOCAL_TRANSLATION_BUNDLES[langCode];
  return !!bundle && Object.keys(bundle).length > 0;
}
