/**
 * Offline locale bundles — one JSON file per supported language.
 * Generated by: node scripts/generate-all-locales.js
 * English source of truth: scripts/en-flat.json → locales/en.json
 */
import en from '../locales/en.json';
import es from '../locales/es.json';
import fr from '../locales/fr.json';
import de from '../locales/de.json';
import it from '../locales/it.json';
import pt from '../locales/pt.json';
import nl from '../locales/nl.json';
import pl from '../locales/pl.json';
import ru from '../locales/ru.json';
import zh from '../locales/zh.json';
import ja from '../locales/ja.json';
import ko from '../locales/ko.json';
import ar from '../locales/ar.json';
import hi from '../locales/hi.json';
import tr from '../locales/tr.json';
import sv from '../locales/sv.json';
import da from '../locales/da.json';
import no from '../locales/no.json';
import fi from '../locales/fi.json';

export const LOCAL_TRANSLATION_BUNDLES: Record<string, Record<string, string>> = {
  en,
  es,
  fr,
  de,
  it,
  pt,
  nl,
  pl,
  ru,
  zh,
  ja,
  ko,
  ar,
  hi,
  tr,
  sv,
  da,
  no,
  fi,
};

/** All supported UI languages with full offline translation coverage */
export const UI_FULL_COVERAGE_LANGUAGES = [
  'en',
  'es',
  'fr',
  'de',
  'it',
  'pt',
  'nl',
  'pl',
  'ru',
  'zh',
  'ja',
  'ko',
  'ar',
  'hi',
  'tr',
  'sv',
  'da',
  'no',
  'fi',
] as const;

export type FullCoverageLanguage = (typeof UI_FULL_COVERAGE_LANGUAGES)[number];

const RTL_LANGUAGES = new Set(['ar']);

export function resolveLocaleDirection(langCode: string): 'ltr' | 'rtl' {
  return RTL_LANGUAGES.has(langCode) ? 'rtl' : 'ltr';
}
